### ISSUE TITLE
Issues with a type of pattern

### ISSUE THREAD

**Issue by cgtorrubia** [robinweser/small-date#5]
Heya! 

I started using your package today and so far so good; however, I encountered an issue, the user will input the date like 12122024 and I was trying to parse it using something like `ddMMyyyy`; however, the package seems to struggle to understand that they are different elements within the pattern (unless I add spaces or break the pattern in different bits). 

Any suggestion that could allow me to format the data like the above?

**Comment by robinweser** [comment]
small-date is not a parsing library. It only formats dates that are either valid `Date` objects or can be parsed using `new Date(value)`. If you want to support a custom format, you need to parse it first.

Here's a quick example:
```ts
import { format } from "small-date"

function parse(date: string) {
  const split = date.match(/([0-9]{2})([0-9]{2})([0-9]{4})/)

  if (split.length === 4) {
    const [_, day, month, year] = split
    return new Date(year, month, day)
  } else {
    throw new Error("Wrong format")
  }
}

const date = parse("12122024")
// => 12 Dec, 2024
const formatted = format(date, "dd MMM, yyyy")
```
